services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  backend:
    container_name: backend
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env.backend
    command: uvicorn app.main:app --host 0.0.0.0 --reload

  db:
    container_name: db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.db
    ports:
      - "5432:5432"

volumes:
  postgres_data: