services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env.frontend
    restart: unless-stopped

  backend:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.backend
    restart: unless-stopped
    command: conda run -n myenv uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: 