FROM python:3.9

WORKDIR /app

RUN pip install --upgrade pip

RUN pip install pdfplumber

RUN pip install sentence_transformers

RUN pip install numpy

RUN pip install langchain langchain-google-genai pypdf

RUN pip install -U langchain-community

RUN pip install langchain-groq python-decouple

RUN pip install textract

RUN pip install PyPDF2

RUN pip install spacy
RUN python -m spacy download en_core_web_sm

RUN pip install --upgrade langchain
RUN pip install --upgrade langchain-core
RUN pip install --upgrade groq

COPY /app/. .

# EXPOSE 8000 

CMD ["python", "main.py"]